const beautyHeroGenerated = new URL("./assets/beauty-hero-generated.jpg", import.meta.url).href;

export const servicePages = [
  {
    id: "legal",
    route: "/legal",
    theme: "legal",
    toolName: "AI法律助手",
    title: "律师 / 专业服务",
    subtitle: "先让客户把问题说清楚，再交给律师承接",
    primaryCta: "咨询律师",
    secondaryCta: "预约面谈",
    intro: "您好，我是您的AI法律助手。有法律问题？先问一问，帮您快速理清事实、证据和处理路径。",
    defaultQuestion: "对方欠我8万元一直不还，我手里有借条和转账记录，应该怎么处理？",
    quickActions: [
      { label: "婚姻家事", caption: "离婚 / 财产 / 子女", icon: "UsersRound", seed: "我想咨询婚姻家事纠纷，先了解需要准备哪些材料。" },
      { label: "劳动纠纷", caption: "离职 / 赔偿 / 合同", icon: "BadgeCheck", seed: "公司拖欠工资并要求我主动离职，我想知道怎么维权。" },
      { label: "合同纠纷", caption: "违约 / 尾款 / 退款", icon: "FileText", seed: "对方合同违约且不退尾款，我需要先做哪些证据整理？" },
      { label: "债权债务", caption: "借款 / 欠款 / 催收", icon: "Scale", seed: "对方欠款不还，我想先判断能否发律师函或起诉。" },
    ],
    flowSteps: [
      { title: "专业内容", caption: "建立信任", icon: "FileText" },
      { title: "AI问题初筛", caption: "先问清楚", icon: "Bot" },
      { title: "材料清单", caption: "证据整理", icon: "ClipboardList" },
      { title: "私域沟通", caption: "持续跟进", icon: "MessagesSquare" },
      { title: "咨询成交", caption: "转化委托", icon: "Handshake" },
      { title: "项目委托", caption: "服务闭环", icon: "BriefcaseBusiness" },
    ],
    result: {
      title: "AI初步分析结果",
      rows: [
        ["问题类型", "债权债务纠纷"],
        ["法律依据", "《民法典》第577条等相关规定"],
        ["可能方案", "协商 / 发律师函 / 起诉"],
        ["所需材料", "借条、转账记录、聊天记录"],
      ],
    },
    actions: [
      { id: "ask", label: "发送问题", detail: "AI已根据事实、证据和诉求生成初步分析，并同步整理材料清单。" },
      { id: "lawyer", label: "咨询律师", detail: "已打开律师咨询卡，可继续填写称呼、电话和方便沟通的时间。" },
      { id: "booking", label: "预约面谈", detail: "已进入线下或视频面谈预约流程，适合高意向客户进一步沟通。" },
      { id: "detail", label: "查看详情", detail: "这里会展示更完整的事实梳理、风险提示、证据缺口和下一步建议。" },
    ],
    tabs: ["首页", "案例", "我的"],
  },
  {
    id: "beauty",
    route: "/beauty",
    theme: "beauty",
    toolName: "AI智能面诊",
    title: "医美智能面诊",
    subtitle: "先给客户低压力体验，再引导领取报告和私域顾问",
    primaryCta: "领取完整报告",
    secondaryCta: "获取定制方案",
    asset: beautyHeroGenerated,
    scanLabels: ["细纹情况", "痘痘情况", "肤色均匀度", "皮肤弹性", "毛孔大小", "敏感程度"],
    quickActions: [
      { label: "温和洁面", caption: "屏障友好", icon: "ShieldCheck" },
      { label: "保湿补水", caption: "稳定状态", icon: "Droplets" },
      { label: "高效抗氧化", caption: "暗沉改善", icon: "Sparkles" },
      { label: "增强睡眠", caption: "修复节律", icon: "MoonStar" },
    ],
    flowSteps: [
      { title: "内容种草", caption: "吸引关注", icon: "Leaf" },
      { title: "AI面诊", caption: "智能分析", icon: "ScanFace" },
      { title: "领取报告", caption: "获取结果", icon: "FileChartLine" },
      { title: "私域顾问", caption: "专业解答", icon: "Headphones" },
      { title: "到店面诊", caption: "线下体验", icon: "Store" },
      { title: "项目成交", caption: "线下转化", icon: "Handshake" },
    ],
    metrics: [
      { label: "细纹", value: 65, tone: "blue" },
      { label: "肤色均匀度", value: 55, tone: "cyan" },
      { label: "痘痘情况", value: 78, tone: "pink" },
      { label: "毛孔大小", value: 60, tone: "purple" },
    ],
    reportHighlights: ["肤质倾向：混合偏干", "优先建议：补水修护", "适合项目：光电紧致评估"],
    actions: [
      { id: "scan", label: "重新扫描", detail: "面部特征点识别中，报告分数会随扫描进度更新。" },
      { id: "report", label: "领取完整报告", detail: "完整报告已生成，可承接加企业微信、留资或顾问跟进。" },
      { id: "advisor", label: "获取定制方案", detail: "已打开顾问方案卡，适合收集预算、地区和改善目标。" },
    ],
    tabs: ["面诊", "报告", "顾问"],
  },
  {
    id: "divination",
    route: "/divination",
    theme: "divination",
    toolName: "国学智能测算",
    title: "国学智能测算",
    subtitle: "用轻量互动吸引兴趣，再引导深度解读与复购",
    primaryCta: "再转一次",
    secondaryCta: "分享结果",
    userName: "Explorer Leo",
    quickActions: [
      { label: "事业运势", caption: "机会与贵人", icon: "BriefcaseBusiness" },
      { label: "感情运势", caption: "关系与沟通", icon: "HeartHandshake" },
      { label: "财富建议", caption: "预算与投入", icon: "Gem" },
      { label: "深度咨询", caption: "专属解读", icon: "MessagesSquare" },
    ],
    flowSteps: [
      { title: "内容种草", caption: "吸引兴趣", icon: "Leaf" },
      { title: "点击测算", caption: "进入体验", icon: "Target" },
      { title: "领取报告", caption: "获取结果", icon: "FileText" },
      { title: "私域顾问", caption: "专业解读", icon: "Headphones" },
      { title: "深度咨询", caption: "建立信任", icon: "MessagesSquare" },
      { title: "项目成交", caption: "转化复购", icon: "Handshake" },
    ],
    fortunes: [
      {
        title: "今日运势解读",
        score: "88",
        items: [
          ["事业运势", "吉星高照，职场遇贵人，宜积极进取，大胆拓展。"],
          ["感情运势", "桃花运佳，沟通顺畅，感情更进一步。"],
        ],
      },
      {
        title: "本周能量提示",
        score: "92",
        items: [
          ["事业运势", "旧资源带来新机会，适合主动联系关键人。"],
          ["财富建议", "宜稳健规划预算，不适合冲动投入。"],
        ],
      },
    ],
    actions: [
      { id: "spin", label: "点击转动", detail: "转盘已启动，新的运势报告会自动刷新。" },
      { id: "share", label: "分享结果", detail: "已生成适合朋友圈和私域群转发的结果卡片。" },
      { id: "consult", label: "深度咨询", detail: "已打开顾问解读入口，承接高意向咨询。" },
    ],
    tabs: ["首页", "历史", "我的"],
  },
];
